#!/usr/bin/env bash
set -euo pipefail

LOG_PATH="${LOG_PATH:-/tmp/idare_script_archival_reproducibility_report.log}"
exec > >(tee "$LOG_PATH") 2>&1

echo "===== 0) start script archival/reproducibility report ====="
date
git status --short --branch
echo

echo "===== 1) choose python and require clean repo ====="
PY="${PY:-.venv/bin/python}"
if [[ ! -x "$PY" ]]; then
  PY="$(command -v python3)"
fi
echo "PY=$PY"
"$PY" - <<'PY'
try:
    import json
    import csv
    from pathlib import Path
    import pandas as pd
except Exception as e:
    raise SystemExit(f"ERROR_IMPORTS: {e}")
print("OK_IMPORTS")
PY

if [[ -n "$(git status --porcelain)" ]]; then
  echo "ERROR: repo is not clean; commit/stash before creating archival outputs." >&2
  git status --short
  exit 2
fi
echo "OK_REPO_CLEAN"
echo

echo "===== 2) check required reproducibility objective and active analysis evidence ====="
required=(
  docs/idare_reproducibility_layer_pause_status.md
  docs/idare_reproducibility_layer_pause_status.json
  docs/idare_script_archival_and_reproducibility_objective.md
  docs/idare_script_archival_and_reproducibility_objective.json
  docs/idare_script_archival_and_reproducibility_policy.csv
  docs/idare_script_archival_and_reproducibility_inventory_seed.csv
  docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md
  docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.json
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_report.md
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_report.json
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_runs.csv
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_predictions.csv
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_metric_summary.csv
  docs/idare_label_semantics_minimal_redesigned_task_first_pass_subject_error_summary.csv
  docs/project_status_current.json
  docs/project_status_current.md
)
for f in "${required[@]}"; do
  if [[ ! -f "$f" ]]; then
    echo "ERROR: missing required input: $f" >&2
    exit 3
  fi
  ls -lh "$f"
done
echo

echo "===== 3) create scripts/idare layout and active read-only analysis script ====="
mkdir -p scripts/idare/analysis scripts/idare/archive_or_reconstructed

cat > scripts/idare/README.md <<'MD'
# I-DARE Script Archive

This directory contains committed, reusable I-DARE workflow scripts.

## Policy

- New I-DARE reports should be generated by scripts committed under this directory, not only by ad-hoc files under `~/Downloads`.
- Each script should reference the objective document it implements.
- Each script should validate inputs and outputs.
- Scripts must not run blocked work unless a reviewed objective explicitly authorizes it.
- Historical scripts may be backfilled only when reconstructable from logs; reconstructed files must be labeled as reconstructed, not original.

## Layout

- `scripts/idare/analysis/`: read-only diagnostic/report scripts.
- `scripts/idare/archive_or_reconstructed/`: optional backfilled historical scripts, only when provenance can be represented honestly.

## Active pause point

The current scientific analysis is paused at:

`docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md`

The next analysis must be run from:

`scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py`

after this reproducibility layer has been reviewed.
MD

cat > scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py <<'PY'
#!/usr/bin/env python3
"""Read-only I-DARE minimal redesigned-task failure-or-confirmation analysis.

Objective:
  docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md

This script performs no training. It consumes committed first-pass outputs and writes
read-only analysis artifacts to docs/.

Expected outputs:
  docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.md
  docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.json
  docs/idare_label_semantics_minimal_redesigned_task_cell_decision_matrix.csv
  docs/idare_label_semantics_minimal_redesigned_task_fold_instability_audit.csv
  docs/idare_label_semantics_minimal_redesigned_task_subject_error_audit.csv
  docs/idare_label_semantics_minimal_redesigned_task_metric_conflict_audit.csv
"""

from __future__ import annotations

import json
import math
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd


DOCS = Path("docs")

OBJECTIVE_MD = DOCS / "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md"
OBJECTIVE_JSON = DOCS / "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.json"

FIRST_PASS_REPORT_JSON = DOCS / "idare_label_semantics_minimal_redesigned_task_first_pass_report.json"
RUNS_CSV = DOCS / "idare_label_semantics_minimal_redesigned_task_first_pass_runs.csv"
PREDICTIONS_CSV = DOCS / "idare_label_semantics_minimal_redesigned_task_first_pass_predictions.csv"
METRIC_SUMMARY_CSV = DOCS / "idare_label_semantics_minimal_redesigned_task_first_pass_metric_summary.csv"
SUBJECT_ERROR_CSV = DOCS / "idare_label_semantics_minimal_redesigned_task_first_pass_subject_error_summary.csv"
PROJECT_STATUS_JSON = DOCS / "project_status_current.json"
PROJECT_STATUS_MD = DOCS / "project_status_current.md"

OUT_REPORT_MD = DOCS / "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.md"
OUT_REPORT_JSON = DOCS / "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.json"
OUT_CELL_MATRIX = DOCS / "idare_label_semantics_minimal_redesigned_task_cell_decision_matrix.csv"
OUT_FOLD_AUDIT = DOCS / "idare_label_semantics_minimal_redesigned_task_fold_instability_audit.csv"
OUT_SUBJECT_AUDIT = DOCS / "idare_label_semantics_minimal_redesigned_task_subject_error_audit.csv"
OUT_METRIC_CONFLICT = DOCS / "idare_label_semantics_minimal_redesigned_task_metric_conflict_audit.csv"


def read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_json(path: Path, obj: Any) -> None:
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def safe_float(value: Any, default: float = float("nan")) -> float:
    try:
        if value is None:
            return default
        return float(value)
    except Exception:
        return default


def bool_to_text(value: bool) -> str:
    return "yes" if bool(value) else "no"


def markdown_table(df: pd.DataFrame, max_rows: int | None = None) -> str:
    """Small dependency-free markdown table writer."""
    if max_rows is not None:
        df = df.head(max_rows)
    if df.empty:
        return "_No rows._"
    shown = df.copy()
    for col in shown.columns:
        shown[col] = shown[col].map(lambda x: "" if pd.isna(x) else str(x))
    cols = list(shown.columns)
    header = "| " + " | ".join(cols) + " |"
    sep = "| " + " | ".join(["---"] * len(cols)) + " |"
    rows = ["| " + " | ".join(str(row[col]) for col in cols) + " |" for _, row in shown.iterrows()]
    return "\n".join([header, sep] + rows)


def require_inputs() -> None:
    required = [
        OBJECTIVE_MD,
        OBJECTIVE_JSON,
        FIRST_PASS_REPORT_JSON,
        RUNS_CSV,
        PREDICTIONS_CSV,
        METRIC_SUMMARY_CSV,
        SUBJECT_ERROR_CSV,
        PROJECT_STATUS_JSON,
        PROJECT_STATUS_MD,
    ]
    missing = [str(p) for p in required if not p.exists()]
    if missing:
        raise SystemExit("ERROR: missing required inputs: " + ", ".join(missing))


def normalize_columns(df: pd.DataFrame) -> pd.DataFrame:
    rename = {}
    if "accuracy" in df.columns and "acc" not in df.columns:
        rename["accuracy"] = "acc"
    if "mean_top_bottom_q33_balanced_accuracy" in df.columns and "mean_q33_bal_acc" not in df.columns:
        rename["mean_top_bottom_q33_balanced_accuracy"] = "mean_q33_bal_acc"
    if "q33_bal_acc" in df.columns and "top_bottom_q33_balanced_accuracy" not in df.columns:
        rename["q33_bal_acc"] = "top_bottom_q33_balanced_accuracy"
    return df.rename(columns=rename)


def build_cell_decision_matrix(runs: pd.DataFrame, first_report: dict[str, Any]) -> pd.DataFrame:
    runs = normalize_columns(runs)
    ridge = runs[runs["model"].astype(str).eq("ridge_regression_summary_features")].copy()
    base = runs[runs["model"].astype(str).eq("mean_baseline_no_training")].copy()

    rows: list[dict[str, Any]] = []
    for (modality, task), g in ridge.groupby(["modality", "task"], dropna=False):
        b = base[(base["modality"].astype(str) == str(modality)) & (base["task"].astype(str) == str(task))]
        mean_s = g["spearman_rho"].mean()
        std_s = g["spearman_rho"].std(ddof=0)
        min_s = g["spearman_rho"].min()
        max_s = g["spearman_rho"].max()
        folds_pos = int((g["spearman_rho"] > 0).sum())
        folds_over_010 = int((g["spearman_rho"] > 0.10).sum())
        folds_under_000 = int((g["spearman_rho"] < 0).sum())
        mean_mae = g["mae"].mean()
        mean_rmse = g["rmse"].mean()
        base_mae = b["mae"].mean() if not b.empty else float("nan")
        base_rmse = b["rmse"].mean() if not b.empty else float("nan")
        delta_mae = base_mae - mean_mae if math.isfinite(base_mae) else float("nan")
        delta_rmse = base_rmse - mean_rmse if math.isfinite(base_rmse) else float("nan")
        mean_q33 = g["q33_bal_acc"].mean() if "q33_bal_acc" in g.columns else float("nan")
        mean_perm = g["permutation_control_spearman"].mean() if "permutation_control_spearman" in g.columns else float("nan")
        confirmable = bool(mean_s > 0.10 and delta_mae > 0 and folds_pos >= 4)
        weak_positive = bool(mean_s > 0 and folds_pos >= 4 and abs(mean_perm) < 0.05)
        metric_conflict = bool(mean_s > 0 and delta_mae <= 0)
        if confirmable:
            decision = "confirmable_signal"
            reason = "mean Spearman exceeds threshold, fold consistency is acceptable, and MAE improves over baseline"
        elif weak_positive and metric_conflict:
            decision = "weak_signal_metric_conflict"
            reason = "Spearman is weakly positive, but MAE/RMSE do not improve over mean baseline"
        elif weak_positive:
            decision = "weak_signal_requires_caution"
            reason = "Spearman is weakly positive but below confirmation threshold"
        else:
            decision = "not_confirmable"
            reason = "Spearman is near zero/unstable and below confirmation threshold"

        rows.append(
            {
                "modality": modality,
                "task": task,
                "n_folds": int(len(g)),
                "mean_spearman_rho": mean_s,
                "std_spearman_rho": std_s,
                "min_spearman_rho": min_s,
                "max_spearman_rho": max_s,
                "folds_positive_spearman": folds_pos,
                "folds_over_010_spearman": folds_over_010,
                "folds_under_000_spearman": folds_under_000,
                "mean_mae": mean_mae,
                "mean_rmse": mean_rmse,
                "mean_baseline_mae": base_mae,
                "mean_baseline_rmse": base_rmse,
                "delta_vs_mean_baseline_mae_positive_is_better": delta_mae,
                "delta_vs_mean_baseline_rmse_positive_is_better": delta_rmse,
                "mean_q33_bal_acc": mean_q33,
                "mean_permutation_control_spearman": mean_perm,
                "decision": decision,
                "reason": reason,
            }
        )
    out = pd.DataFrame(rows)
    if not out.empty:
        out = out.sort_values(
            ["decision", "mean_spearman_rho", "delta_vs_mean_baseline_mae_positive_is_better"],
            ascending=[True, False, False],
        )
    return out


def build_fold_instability_audit(runs: pd.DataFrame) -> pd.DataFrame:
    runs = normalize_columns(runs)
    ridge = runs[runs["model"].astype(str).eq("ridge_regression_summary_features")].copy()
    rows: list[dict[str, Any]] = []
    for _, r in ridge.iterrows():
        s = safe_float(r.get("spearman_rho"))
        mae = safe_float(r.get("mae"))
        rmse = safe_float(r.get("rmse"))
        q33 = safe_float(r.get("q33_bal_acc"))
        perm = safe_float(r.get("permutation_control_spearman"), 0.0)
        flags = []
        if s > 0.10:
            flags.append("positive_above_confirmation_threshold")
        elif s > 0:
            flags.append("weak_positive")
        else:
            flags.append("non_positive")
        if abs(perm) >= 0.05:
            flags.append("permutation_control_nonzero")
        if q33 < 0.48 or q33 > 0.55:
            flags.append("q33_deviation_from_chance")
        rows.append(
            {
                "objective_run_id": r.get("objective_run_id"),
                "modality": r.get("modality"),
                "task": r.get("task"),
                "fold": r.get("fold"),
                "spearman_rho": s,
                "mae": mae,
                "rmse": rmse,
                "q33_bal_acc": q33,
                "permutation_control_spearman": perm,
                "flags": ";".join(flags),
            }
        )
    out = pd.DataFrame(rows)
    if not out.empty:
        out = out.sort_values(["modality", "task", "spearman_rho"], ascending=[True, True, False])
    return out


def build_metric_conflict_audit(cell: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    for _, r in cell.iterrows():
        mean_s = safe_float(r.get("mean_spearman_rho"))
        delta_mae = safe_float(r.get("delta_vs_mean_baseline_mae_positive_is_better"))
        delta_rmse = safe_float(r.get("delta_vs_mean_baseline_rmse_positive_is_better"))
        q33 = safe_float(r.get("mean_q33_bal_acc"))
        perm = safe_float(r.get("mean_permutation_control_spearman"))
        conflict = []
        if mean_s > 0 and delta_mae <= 0:
            conflict.append("positive_spearman_but_mae_worse")
        if mean_s > 0 and delta_rmse <= 0:
            conflict.append("positive_spearman_but_rmse_worse")
        if mean_s <= 0:
            conflict.append("no_positive_rank_signal")
        if abs(perm) >= 0.05:
            conflict.append("permutation_control_not_near_zero")
        if q33 < 0.49 or q33 > 0.53:
            conflict.append("q33_not_strict_chance")
        rows.append(
            {
                "modality": r.get("modality"),
                "task": r.get("task"),
                "mean_spearman_rho": mean_s,
                "delta_mae_positive_is_better": delta_mae,
                "delta_rmse_positive_is_better": delta_rmse,
                "mean_q33_bal_acc": q33,
                "mean_permutation_control_spearman": perm,
                "metric_conflict_flags": ";".join(conflict) if conflict else "none",
                "confirmability": r.get("decision"),
            }
        )
    return pd.DataFrame(rows)


def build_subject_error_audit(subjects: pd.DataFrame) -> pd.DataFrame:
    df = subjects.copy()
    if df.empty:
        return pd.DataFrame()

    # Make the audit robust to small naming changes.
    numeric_cols = [c for c in df.columns if pd.api.types.is_numeric_dtype(df[c])]
    group_cols = [c for c in ["model", "modality", "task", "subject", "subject_id"] if c in df.columns]
    subject_col = "subject" if "subject" in df.columns else ("subject_id" if "subject_id" in df.columns else None)
    if subject_col is None:
        df["subject"] = range(len(df))
        subject_col = "subject"

    err_candidates = [
        "mean_abs_error",
        "mae",
        "abs_error",
        "rank_abs_error",
        "subject_mae",
        "mean_mae",
    ]
    err_col = next((c for c in err_candidates if c in df.columns), None)
    if err_col is None:
        # fallback to the last numeric column so the report still exposes hard rows
        err_col = numeric_cols[-1] if numeric_cols else None

    if err_col is None:
        return df.head(50).copy()

    agg_cols = [c for c in ["model", "modality", "task", subject_col] if c in df.columns]
    out = (
        df.groupby(agg_cols, dropna=False)[err_col]
        .agg(["mean", "max", "count"])
        .reset_index()
        .rename(columns={"mean": "mean_error", "max": "max_error", "count": "n_rows"})
    )
    out["hard_subject_flag"] = out["mean_error"] >= out["mean_error"].quantile(0.90)
    out = out.sort_values(["hard_subject_flag", "mean_error"], ascending=[False, False])
    return out


def decide_next(cell: pd.DataFrame, conflict: pd.DataFrame) -> tuple[str, str, str]:
    if cell.empty:
        return (
            "minimal_redesigned_task_first_pass_uninterpretable",
            "label_semantics_redesigned_task_stop_archive_objective",
            "No cell-level evidence was available.",
        )

    confirmable = cell[cell["decision"].eq("confirmable_signal")]
    weak = cell[cell["decision"].astype(str).str.contains("weak_signal", na=False)]
    best = cell.sort_values("mean_spearman_rho", ascending=False).iloc[0]
    best_s = safe_float(best.get("mean_spearman_rho"))
    best_delta_mae = safe_float(best.get("delta_vs_mean_baseline_mae_positive_is_better"))
    best_folds_pos = int(best.get("folds_positive_spearman", 0))

    if not confirmable.empty:
        return (
            "minimal_redesigned_task_first_pass_confirmable",
            "label_semantics_minimal_redesigned_task_confirmation_objective",
            "At least one cell crossed the confirmation threshold and improved error metrics.",
        )

    if best_s > 0 and best_folds_pos >= 4 and best_delta_mae <= 0:
        return (
            "minimal_redesigned_task_weak_rank_signal_metric_conflict",
            "label_semantics_redesigned_task_metric_debug_objective",
            "The best cell has weak positive rank signal but worsens MAE/RMSE against mean baseline.",
        )

    if not weak.empty:
        return (
            "minimal_redesigned_task_weak_signal_not_confirmable",
            "label_semantics_minimal_redesigned_task_targeted_confirmation_design_objective",
            "There is weak positive signal but it is below threshold and requires a narrow confirmation design, not broad training.",
        )

    return (
        "minimal_redesigned_task_first_pass_not_confirmed",
        "label_semantics_redesigned_task_stop_archive_objective",
        "No robust positive rank signal was found.",
    )


def update_project_status(diagnosis: str, next_obj: str, reason: str, now: str) -> None:
    status = read_json(PROJECT_STATUS_JSON)
    blocked = [
        "direct full SupCon/DG training",
        "broad hyperparameter search",
        "EEG+EMG fusion",
        "final LOSO claim",
        "mainline change",
        "deep neural training for redesigned task",
        "unregistered feature engineering",
    ]
    status["last_updated_utc"] = now
    status["current_idare_next_allowed_step"] = f"human_review_closeout_then_create_{next_obj}"
    status["current_idare_blocked_steps"] = blocked
    events = status.get("idare_protocol_events")
    if not isinstance(events, list):
        events = []
    status["idare_protocol_events"] = events
    events.append(
        {
            "timestamp_utc": now,
            "type": "analysis_report",
            "name": "I-DARE minimal redesigned-task failure-or-confirmation analysis report",
            "status": f"complete pending human review; diagnosis={diagnosis}",
            "evidence": str(OUT_REPORT_MD),
            "next_allowed_step": f"Human review / closeout before {next_obj}.",
            "blocked": blocked,
        }
    )
    write_json(PROJECT_STATUS_JSON, status)

    md = PROJECT_STATUS_MD.read_text(encoding="utf-8")
    append = f"""

## I-DARE Minimal Redesigned-Task Failure-or-Confirmation Analysis Report

Updated: `{now}`

| Item | Status | Evidence | Next allowed step | Blocked |
|---|---|---|---|---|
| I-DARE minimal redesigned-task failure-or-confirmation analysis report | complete pending human review; diagnosis=`{diagnosis}` | `docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.md` | Human review / closeout before `{next_obj}`. | direct full SupCon/DG training; broad hyperparameter search; EEG+EMG fusion; final LOSO claim; mainline change |

- Decision reason: {reason}
- Recommended next objective is `{next_obj}` only after human review/closeout.
"""
    if "I-DARE Minimal Redesigned-Task Failure-or-Confirmation Analysis Report" not in md:
        PROJECT_STATUS_MD.write_text(md.rstrip() + append + "\n", encoding="utf-8")


def main() -> None:
    require_inputs()
    now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

    objective = read_json(OBJECTIVE_JSON)
    first_report = read_json(FIRST_PASS_REPORT_JSON)
    if objective.get("training_authorized") is not False:
        raise SystemExit("ERROR: objective must be read-only with training_authorized=false")
    if first_report.get("diagnosis") != "minimal_redesigned_task_first_pass_mixed_signal":
        raise SystemExit("ERROR: first-pass diagnosis does not match expected mixed signal")

    runs = pd.read_csv(RUNS_CSV)
    # Confirm predictions are readable and row count is available; no need to hold full contents longer than needed.
    n_predictions = sum(1 for _ in open(PREDICTIONS_CSV, "r", encoding="utf-8")) - 1
    metric = pd.read_csv(METRIC_SUMMARY_CSV)
    subject = pd.read_csv(SUBJECT_ERROR_CSV)

    required_run_cols = {"model", "modality", "task", "fold", "spearman_rho", "mae", "rmse"}
    missing = required_run_cols - set(runs.columns)
    if missing:
        raise SystemExit(f"ERROR: runs CSV missing required columns: {sorted(missing)}")

    cell = build_cell_decision_matrix(runs, first_report)
    fold = build_fold_instability_audit(runs)
    conflict = build_metric_conflict_audit(cell)
    subject_audit = build_subject_error_audit(subject)
    diagnosis, next_obj, reason = decide_next(cell, conflict)

    cell.to_csv(OUT_CELL_MATRIX, index=False)
    fold.to_csv(OUT_FOLD_AUDIT, index=False)
    conflict.to_csv(OUT_METRIC_CONFLICT, index=False)
    subject_audit.to_csv(OUT_SUBJECT_AUDIT, index=False)

    best = cell.sort_values("mean_spearman_rho", ascending=False).iloc[0].to_dict() if not cell.empty else {}
    key = {
        "n_runs": int(len(runs)),
        "n_predictions": int(n_predictions),
        "n_metric_summary_rows": int(len(metric)),
        "n_subject_error_rows": int(len(subject)),
        "best_cell": best,
        "n_confirmable_cells": int((cell["decision"] == "confirmable_signal").sum()) if not cell.empty else 0,
        "n_weak_signal_cells": int(cell["decision"].astype(str).str.contains("weak_signal", na=False).sum()) if not cell.empty else 0,
        "n_metric_conflict_cells": int(conflict["metric_conflict_flags"].astype(str).str.contains("mae_worse|rmse_worse", regex=True).sum()) if not conflict.empty else 0,
    }

    report = {
        "status": "complete_pending_human_review",
        "created_utc": now,
        "objective": str(OBJECTIVE_MD),
        "source_first_pass_report": str(FIRST_PASS_REPORT_JSON),
        "diagnosis": diagnosis,
        "recommended_next_objective": next_obj,
        "decision_reason": reason,
        "key_indicators": key,
        "outputs": {
            "cell_decision_matrix": str(OUT_CELL_MATRIX),
            "fold_instability_audit": str(OUT_FOLD_AUDIT),
            "subject_error_audit": str(OUT_SUBJECT_AUDIT),
            "metric_conflict_audit": str(OUT_METRIC_CONFLICT),
        },
        "training_authorized": False,
    }
    write_json(OUT_REPORT_JSON, report)

    cell_show = cell.copy()
    if not cell_show.empty:
        for c in [
            "mean_spearman_rho",
            "std_spearman_rho",
            "delta_vs_mean_baseline_mae_positive_is_better",
            "mean_q33_bal_acc",
            "mean_permutation_control_spearman",
        ]:
            if c in cell_show.columns:
                cell_show[c] = cell_show[c].map(lambda x: f"{x:.4f}" if pd.notna(x) else "")
        cell_show = cell_show[
            [
                "modality",
                "task",
                "mean_spearman_rho",
                "folds_positive_spearman",
                "folds_over_010_spearman",
                "delta_vs_mean_baseline_mae_positive_is_better",
                "mean_q33_bal_acc",
                "decision",
            ]
        ]

    conflict_show = conflict.copy()
    if not conflict_show.empty:
        for c in ["mean_spearman_rho", "delta_mae_positive_is_better", "delta_rmse_positive_is_better", "mean_q33_bal_acc"]:
            if c in conflict_show.columns:
                conflict_show[c] = conflict_show[c].map(lambda x: f"{x:.4f}" if pd.notna(x) else "")
        conflict_show = conflict_show[
            [
                "modality",
                "task",
                "mean_spearman_rho",
                "delta_mae_positive_is_better",
                "delta_rmse_positive_is_better",
                "mean_q33_bal_acc",
                "metric_conflict_flags",
            ]
        ]

    md = f"""# I-DARE Minimal Redesigned-Task Failure-or-Confirmation Analysis Report

## Status

Status: complete; pending human review.

Created UTC: `{now}`

## Executive Diagnosis

Diagnosis: `{diagnosis}`

Recommended next objective: `{next_obj}`

Decision reason: {reason}

## Cell Decision Matrix

{markdown_table(cell_show)}

## Metric Conflict Audit

{markdown_table(conflict_show)}

## Fold Instability Interpretation

The first-pass result is interpreted from ridge regression cells only, against the no-training mean baseline and permutation control.

The analysis checks whether positive Spearman is robust across folds, whether MAE/RMSE improve over baseline, and whether q33 balanced accuracy is consistent with the rank-order signal.

## Subject Error Audit

Subject-level errors were summarized in `docs/idare_label_semantics_minimal_redesigned_task_subject_error_audit.csv`.

Rows in source subject-error file: `{len(subject)}`

## Interpretation

This report does not authorize training.

Confirmation requires both a rank-order signal and no major conflict with error metrics. A weak positive Spearman with worse MAE/RMSE is treated as a metric conflict rather than confirmation.

## Next Allowed Step

Human review / closeout before `{next_obj}`.

## Blocked

- direct full SupCon/DG training
- broad hyperparameter search
- EEG+EMG fusion
- final LOSO claim
- mainline change
- deep neural training for redesigned task
- unregistered feature engineering
"""
    OUT_REPORT_MD.write_text(md, encoding="utf-8")
    update_project_status(diagnosis, next_obj, reason, now)

    print("OK_FAILURE_OR_CONFIRMATION_ANALYSIS_REPORT_WRITTEN")
    print(OUT_REPORT_MD)
    print(OUT_REPORT_JSON)
    print(OUT_CELL_MATRIX)
    print(OUT_FOLD_AUDIT)
    print(OUT_SUBJECT_AUDIT)
    print(OUT_METRIC_CONFLICT)
    print("diagnosis=", diagnosis)
    print("recommended_next_objective=", next_obj)
    print("decision_reason=", reason)


if __name__ == "__main__":
    main()
PY

chmod +x scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py

echo "OK_SCRIPT_LAYOUT_WRITTEN"
ls -lh scripts/idare/README.md scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py
echo

echo "===== 4) create manifest + reproducibility report ====="
"$PY" - <<'PY'
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path
import pandas as pd

DOCS = Path("docs")
now = datetime.now(timezone.utc).replace(microsecond=0).isoformat()

objective_md = DOCS / "idare_script_archival_and_reproducibility_objective.md"
objective_json = DOCS / "idare_script_archival_and_reproducibility_objective.json"
pause_md = DOCS / "idare_reproducibility_layer_pause_status.md"
active_objective = DOCS / "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md"
manifest_csv = DOCS / "idare_script_archival_manifest.csv"
report_md = DOCS / "idare_script_archival_and_reproducibility_report.md"
report_json = DOCS / "idare_script_archival_and_reproducibility_report.json"
status_json_path = DOCS / "project_status_current.json"
status_md_path = DOCS / "project_status_current.md"

script_path = Path("scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py")
readme_path = Path("scripts/idare/README.md")

def read_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))

def write_json(path, obj):
    Path(path).write_text(json.dumps(obj, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

def git(args):
    return subprocess.check_output(["git"] + args, text=True).strip()

head = git(["rev-parse", "--short", "HEAD"])
objective = read_json(objective_json)
if objective.get("training_authorized") is not False:
    raise SystemExit("ERROR: objective training_authorized is not false")

required_files = [readme_path, script_path]
missing = [str(p) for p in required_files if not p.exists()]
if missing:
    raise SystemExit("ERROR: missing required scripts: " + ", ".join(missing))

script_text = script_path.read_text(encoding="utf-8")
required_terms = [
    "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md",
    "This script performs no training",
    "OUT_REPORT_MD",
    "build_cell_decision_matrix",
]
for term in required_terms:
    if term not in script_text:
        raise SystemExit(f"ERROR: active analysis script missing term {term!r}")

manifest_rows = [
    {
        "manifest_id": "M001",
        "script_path": str(readme_path),
        "script_type": "readme",
        "provenance": "new_committed_reproducibility_layer",
        "source_objective": str(objective_md),
        "command": "cat scripts/idare/README.md",
        "expected_outputs": "",
        "status": "created",
        "notes": "Documents I-DARE script archival policy and layout.",
    },
    {
        "manifest_id": "M002",
        "script_path": str(script_path),
        "script_type": "read_only_analysis",
        "provenance": "new_committed_reproducibility_layer",
        "source_objective": str(active_objective),
        "command": f"{script_path}",
        "expected_outputs": ";".join([
            "docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.md",
            "docs/idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_report.json",
            "docs/idare_label_semantics_minimal_redesigned_task_cell_decision_matrix.csv",
            "docs/idare_label_semantics_minimal_redesigned_task_fold_instability_audit.csv",
            "docs/idare_label_semantics_minimal_redesigned_task_subject_error_audit.csv",
            "docs/idare_label_semantics_minimal_redesigned_task_metric_conflict_audit.csv",
        ]),
        "status": "created_not_yet_run",
        "notes": "Active paused analysis can run from this committed script after human review.",
    },
    {
        "manifest_id": "M003",
        "script_path": "scripts/idare/archive_or_reconstructed/",
        "script_type": "historical_backfill_area",
        "provenance": "placeholder_only",
        "source_objective": str(objective_md),
        "command": "",
        "expected_outputs": "",
        "status": "available_for_future_reconstructable_backfill",
        "notes": "Historical ~/Downloads scripts must be labeled reconstructed_from_log if backfilled.",
    },
]
pd.DataFrame(manifest_rows).to_csv(manifest_csv, index=False)

blocked = [
    "direct full SupCon/DG training",
    "broad hyperparameter search",
    "EEG+EMG fusion",
    "final LOSO claim",
    "mainline change unrelated to script archival",
    "deep neural training for redesigned task",
    "unregistered feature engineering",
]

report = {
    "status": "complete_pending_human_review",
    "created_utc": now,
    "source_objective": str(objective_md),
    "source_pause_status": str(pause_md),
    "repo_head_before_commit": head,
    "created_files": [str(readme_path), str(script_path), str(manifest_csv)],
    "active_analysis_script": str(script_path),
    "active_analysis_status": "created_not_yet_run",
    "diagnosis": "reproducibility_layer_fixed_for_active_next_step",
    "recommended_next_objective": "run_committed_failure_or_confirmation_analysis_after_review",
    "historical_backfill_policy": "only_if_reconstructable_from_logs_and_labeled_reconstructed_from_log",
    "training_authorized": False,
    "blocked": blocked,
}
write_json(report_json, report)

md = f"""# I-DARE Script Archival and Reproducibility Report

## Status

Status: complete; pending human review.

Created UTC: `{now}`

## Executive Result

Diagnosis: `reproducibility_layer_fixed_for_active_next_step`

Recommended next objective: `run_committed_failure_or_confirmation_analysis_after_review`

The active next analysis script is now committed under `scripts/idare/analysis/` and linked to its objective through `docs/idare_script_archival_manifest.csv`.

## Created Script Assets

| Asset | Status | Purpose |
|---|---|---|
| `scripts/idare/README.md` | created | Documents script archival policy and layout. |
| `scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py` | created, not yet run | Read-only active analysis script for the paused failure-or-confirmation objective. |
| `docs/idare_script_archival_manifest.csv` | created | Links objective, script, command, expected outputs, and provenance. |

## Historical Backfill Policy

Historical `~/Downloads` scripts are **not** silently treated as original committed scripts.

They may be backfilled only when reconstructable from logs, and must be labeled:

`reconstructed_from_log`

or:

`not_original_download_file`

## Active Analysis Command After Review

```bash
cd /mnt/HDD/AliWorks/EmotionRecognitionDEAP-I-DARE
scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py
```

## Interpretation

The reproducibility layer is now fixed for the active next step.

No analysis or training was executed by this archival command.

## Next Allowed Step

Human review / closeout, then run the committed failure-or-confirmation analysis script.

## Blocked

- direct full SupCon/DG training
- broad hyperparameter search
- EEG+EMG fusion
- final LOSO claim
- mainline change unrelated to script archival
- deep neural training for redesigned task
- unregistered feature engineering
"""
report_md.write_text(md, encoding="utf-8")

status = read_json(status_json_path)
status["last_updated_utc"] = now
status["current_idare_next_allowed_step"] = "human_review_closeout_then_run_committed_failure_or_confirmation_analysis_script"
status["current_idare_blocked_steps"] = blocked
events = status.get("idare_protocol_events")
if not isinstance(events, list):
    events = []
status["idare_protocol_events"] = events
events.append(
    {
        "timestamp_utc": now,
        "type": "reproducibility_report",
        "name": "I-DARE script archival and reproducibility report",
        "status": "complete pending human review; active analysis script committed but not run",
        "evidence": str(report_md),
        "next_allowed_step": "Human review / closeout, then run committed failure-or-confirmation analysis script.",
        "blocked": blocked,
    }
)
write_json(status_json_path, status)

status_md = status_md_path.read_text(encoding="utf-8")
append = f"""

## I-DARE Script Archival and Reproducibility Report

Updated: `{now}`

| Item | Status | Evidence | Next allowed step | Blocked |
|---|---|---|---|---|
| I-DARE script archival and reproducibility report | complete pending human review; active script committed but not run | `docs/idare_script_archival_and_reproducibility_report.md` | Human review / closeout, then run committed failure-or-confirmation analysis script. | direct full SupCon/DG training; broad hyperparameter search; EEG+EMG fusion; final LOSO claim; deep neural training |

- Active analysis script: `scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py`
- Historical backfill remains allowed only when reconstructable from logs and labeled honestly.
"""
if "I-DARE Script Archival and Reproducibility Report" not in status_md:
    status_md_path.write_text(status_md.rstrip() + append + "\n", encoding="utf-8")

print("OK_SCRIPT_ARCHIVAL_REPRODUCIBILITY_REPORT_WRITTEN")
print(report_md)
print(report_json)
print(manifest_csv)
print("active_analysis_script=", script_path)
print("diagnosis=reproducibility_layer_fixed_for_active_next_step")
print("recommended_next_objective=run_committed_failure_or_confirmation_analysis_after_review")
PY
echo

echo "===== 5) validate archival outputs ====="
"$PY" - <<'PY'
import json
from pathlib import Path
import pandas as pd

required = [
    Path("scripts/idare/README.md"),
    Path("scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py"),
    Path("docs/idare_script_archival_manifest.csv"),
    Path("docs/idare_script_archival_and_reproducibility_report.md"),
    Path("docs/idare_script_archival_and_reproducibility_report.json"),
]
for p in required:
    if not p.exists():
        raise SystemExit(f"ERROR: missing output {p}")
    print("OK_EXISTS:", p)

for p in [
    Path("docs/idare_script_archival_and_reproducibility_report.json"),
    Path("docs/project_status_current.json"),
]:
    json.loads(p.read_text(encoding="utf-8"))
    print("OK_JSON:", p)

manifest = pd.read_csv("docs/idare_script_archival_manifest.csv")
print("manifest_rows=", len(manifest))
if len(manifest) < 2:
    raise SystemExit("ERROR: manifest too short")
if "scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py" not in set(manifest["script_path"].astype(str)):
    raise SystemExit("ERROR: active script missing from manifest")

script_text = Path("scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py").read_text(encoding="utf-8")
for term in [
    "This script performs no training",
    "idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis_objective.md",
    "OUT_CELL_MATRIX",
    "update_project_status",
]:
    if term not in script_text:
        raise SystemExit(f"ERROR: active script missing term {term!r}")
print("OK_ACTIVE_SCRIPT_TERMS")

report = json.loads(Path("docs/idare_script_archival_and_reproducibility_report.json").read_text(encoding="utf-8"))
if report.get("training_authorized") is not False:
    raise SystemExit("ERROR: training_authorized must be false")
if report.get("diagnosis") != "reproducibility_layer_fixed_for_active_next_step":
    raise SystemExit("ERROR: wrong diagnosis")
print("diagnosis=", report["diagnosis"])
print("recommended_next_objective=", report["recommended_next_objective"])
print("ALL_SCRIPT_ARCHIVAL_REPRODUCIBILITY_OUTPUTS_VALID")
PY

grep -nE "Status|Executive Result|Created Script Assets|Historical Backfill Policy|Active Analysis Command|Next Allowed Step" \
  docs/idare_script_archival_and_reproducibility_report.md
echo

echo "===== 6) file list ====="
ls -lh \
  scripts/idare/README.md \
  scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py \
  docs/idare_script_archival_manifest.csv \
  docs/idare_script_archival_and_reproducibility_report.md \
  docs/idare_script_archival_and_reproducibility_report.json \
  docs/project_status_current.json \
  docs/project_status_current.md
echo

echo "===== 7) status before commit ====="
git status --short --branch
echo

echo "===== 8) commit and push archival outputs ====="
git add \
  scripts/idare/README.md \
  scripts/idare/analysis/run_idare_label_semantics_minimal_redesigned_task_failure_or_confirmation_analysis.py \
  docs/idare_script_archival_manifest.csv \
  docs/idare_script_archival_and_reproducibility_report.md \
  docs/idare_script_archival_and_reproducibility_report.json \
  docs/project_status_current.json \
  docs/project_status_current.md

git commit -m "scripts: archive I-DARE reproducibility workflow"
git push origin main
echo

echo "===== 9) final status ====="
git status --short --branch
echo "LOG_SAVED_TO=$LOG_PATH"
