#!/usr/bin/env python3
"""
Validate the I-DARE PyTorch loader.

Outputs:
- docs/idare_loader_validation.md
- docs/idare_loader_validation.json

This script does not train models.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import torch
from torch.utils.data import DataLoader

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from emotion_deap_idare.datasets import IDARETrialDataset, summarize_dataset  # noqa: E402


OUT_MD = ROOT / "docs" / "idare_loader_validation.md"
OUT_JSON = ROOT / "docs" / "idare_loader_validation.json"


EXPECTED_COUNTS = {
    "valence": 1667,
    "arousal": 1799,
}


def tensor_shape(value: Any) -> list[int] | None:
    if isinstance(value, torch.Tensor):
        return list(value.shape)
    return None


def validate_task(task: str) -> dict[str, Any]:
    dataset = IDARETrialDataset(task=task, return_mode="both")

    issues: list[str] = []
    warnings: list[str] = []

    expected_rows = EXPECTED_COUNTS[task]
    if len(dataset) != expected_rows:
        issues.append(f"{task}: expected {expected_rows} rows after score==5 discard, got {len(dataset)}")

    if dataset.df["subject_id"].nunique() != 63:
        issues.append(f"{task}: expected 63 subjects, got {dataset.df['subject_id'].nunique()}")

    summary = summarize_dataset(dataset, n_items_to_check=8)

    for item in summary["checked_items"]:
        if item.get("eeg_shape") != [32, 640]:
            issues.append(f"{task}: bad EEG shape at index {item['index']}: {item.get('eeg_shape')}")
        if item.get("emg_shape") != [2, 10000]:
            issues.append(f"{task}: bad EMG shape at index {item['index']}: {item.get('emg_shape')}")
        if item.get("eeg_isfinite") is not True:
            issues.append(f"{task}: non-finite EEG at index {item['index']}")
        if item.get("emg_isfinite") is not True:
            issues.append(f"{task}: non-finite EMG at index {item['index']}")

    loader = DataLoader(dataset, batch_size=4, shuffle=False, num_workers=0)
    batch = next(iter(loader))

    batch_summary = {
        "eeg_shape": tensor_shape(batch.get("eeg")),
        "emg_shape": tensor_shape(batch.get("emg")),
        "label_shape": tensor_shape(batch.get("label")),
        "label_values": batch["label"].tolist(),
        "eeg_isfinite": bool(torch.isfinite(batch["eeg"]).all().item()),
        "emg_isfinite": bool(torch.isfinite(batch["emg"]).all().item()),
    }

    if batch_summary["eeg_shape"] != [4, 32, 640]:
        issues.append(f"{task}: bad batch EEG shape: {batch_summary['eeg_shape']}")
    if batch_summary["emg_shape"] != [4, 2, 10000]:
        issues.append(f"{task}: bad batch EMG shape: {batch_summary['emg_shape']}")
    if batch_summary["label_shape"] != [4]:
        issues.append(f"{task}: bad batch label shape: {batch_summary['label_shape']}")

    summary["batch_summary"] = batch_summary
    summary["issues"] = issues
    summary["warnings"] = warnings
    summary["status"] = "PASSED" if not issues else "FAILED"

    return summary


def write_markdown(payload: dict[str, Any]) -> None:
    lines: list[str] = []

    lines.append("# I-DARE Loader Validation")
    lines.append("")
    lines.append("This report was generated by `scripts/08_validate_idare_loader.py`.")
    lines.append("")
    lines.append("No model training was performed.")
    lines.append("")
    lines.append("## Status")
    lines.append("")
    lines.append(f"Status: **{payload['status']}**")
    lines.append("")
    lines.append("## Design Being Validated")
    lines.append("")
    lines.append("- Main subject set: 63 common EEG+EMG subjects.")
    lines.append("- Task labels: `label = 1 if score > 5 else 0`; `score == 5` discarded per task.")
    lines.append("- Trial unit: one I-DARE emotional `STIM_*` event.")
    lines.append("- Slicing policy: start at `event_begin`, extract exactly 5.0 seconds.")
    lines.append("- EEG source: 512Hz, first 32 channels, downsampled by 4 to 128Hz.")
    lines.append("- EEG tensor shape: `[32, 640]`.")
    lines.append("- EMG source: 2000Hz, two channels.")
    lines.append("- EMG tensor shape: `[2, 10000]`.")
    lines.append("")

    for task, result in payload["tasks"].items():
        lines.append(f"## Task: `{task}`")
        lines.append("")
        lines.append(f"- Status: **{result['status']}**")
        lines.append(f"- Rows after discard: `{result['n_rows']}`")
        lines.append(f"- Subjects: `{result['n_subjects']}`")
        lines.append(f"- Label counts: `{result['label_counts']}`")
        lines.append("")
        lines.append("### Batch Smoke Test")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(result["batch_summary"], indent=2, ensure_ascii=False))
        lines.append("```")
        lines.append("")
        lines.append("### Checked Item Preview")
        lines.append("")
        lines.append("```json")
        lines.append(json.dumps(result["checked_items"][:4], indent=2, ensure_ascii=False))
        lines.append("```")
        lines.append("")
        lines.append("### Issues")
        lines.append("")
        if result["issues"]:
            for issue in result["issues"]:
                lines.append(f"- {issue}")
        else:
            lines.append("- None.")
        lines.append("")
        lines.append("### Warnings")
        lines.append("")
        if result["warnings"]:
            for warning in result["warnings"]:
                lines.append(f"- {warning}")
        else:
            lines.append("- None.")
        lines.append("")

    lines.append("## Next Step")
    lines.append("")
    lines.append("Use this validated loader to run an I-DARE EEG-only baseline smoke test. Do not start full experiment training until the baseline smoke test is documented.")
    lines.append("")

    OUT_MD.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    tasks = {
        "valence": validate_task("valence"),
        "arousal": validate_task("arousal"),
    }

    issues = []
    warnings = []
    for result in tasks.values():
        issues.extend(result["issues"])
        warnings.extend(result["warnings"])

    payload = {
        "status": "PASSED" if not issues else "FAILED",
        "tasks": tasks,
        "issues": issues,
        "warnings": warnings,
    }

    OUT_JSON.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
    write_markdown(payload)

    print(f"Wrote: {OUT_MD}")
    print(f"Wrote: {OUT_JSON}")
    print(f"Status: {payload['status']}")
    print(f"Issues: {len(issues)}")
    print(f"Warnings: {len(warnings)}")

    for task, result in tasks.items():
        print(f"{task}: rows={result['n_rows']} subjects={result['n_subjects']} labels={result['label_counts']}")

    if issues:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
