#!/usr/bin/env python3
"""Build a fast NumPy cache of I-DARE EEG windows.

Outputs:
- .cache/idare_eeg_windows_32x640_float32.npy
- .cache/idare_eeg_cache_index.csv
- docs/idare_eeg_cache_build_report.md/json

No training is performed.
"""
from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path
from typing import Any

import h5py
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = ROOT / ".cache"
TRIAL_INDEX = CACHE_DIR / "idare_trial_index.csv"
OUT_NPY = CACHE_DIR / "idare_eeg_windows_32x640_float32.npy"
OUT_INDEX = CACHE_DIR / "idare_eeg_cache_index.csv"
OUT_JSON = ROOT / "docs" / "idare_eeg_cache_build_report.json"
OUT_MD = ROOT / "docs" / "idare_eeg_cache_build_report.md"

SOURCE_FS = 512.0
TARGET_FS = 128.0
SOURCE_SAMPLES = 2560
TARGET_SAMPLES = 640
TARGET_CHANNELS = 32
DOWNSAMPLE = 4
POLICIES = ["discard_midpoint", "midpoint_as_low", "midpoint_as_high"]
TASKS = ["valence", "arousal"]


def safe(v: Any) -> Any:
    if isinstance(v, dict):
        return {str(k): safe(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [safe(x) for x in v]
    if isinstance(v, np.ndarray):
        return safe(v.tolist())
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return None if math.isnan(float(v)) else float(v)
    try:
        if pd.isna(v):
            return None
    except Exception:
        pass
    return v


def human_size(n: int | float) -> str:
    n = float(n)
    for unit in ["B", "KB", "MB", "GB", "TB"]:
        if n < 1024 or unit == "TB":
            return f"{n:.2f} {unit}"
        n /= 1024
    return f"{n:.2f} TB"


def subject_key(h5: h5py.File, preferred: str) -> str:
    if preferred in h5:
        return preferred
    cands = sorted(k for k in h5.keys() if k.startswith("sbj_P_"))
    if not cands:
        raise KeyError(f"No sbj_P_* group found. Keys={list(h5.keys())}")
    return cands[0]


def label_from_score(score: Any, policy: str) -> int | None:
    if score is None or pd.isna(score):
        return None
    s = float(score)
    if policy == "discard_midpoint":
        return None if s == 5.0 else int(s > 5.0)
    if policy == "midpoint_as_low":
        return int(s > 5.0)
    if policy == "midpoint_as_high":
        return int(s >= 5.0)
    raise ValueError(policy)


def label_counts(df: pd.DataFrame, task: str, policy: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for score in df[f"{task}_score"].tolist():
        label = label_from_score(score, policy)
        key = "discard" if label is None else str(label)
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items()))


def extract_window(data: h5py.Dataset, begin_raw: float) -> np.ndarray:
    start = int(begin_raw)
    stop = start + SOURCE_SAMPLES
    shape = tuple(int(x) for x in data.shape)
    if len(shape) != 2:
        raise ValueError(f"Expected 2D data, got {shape}")

    if shape[0] >= stop and shape[1] >= TARGET_CHANNELS:
        # time x channels, which matches the I-DARE h5py probe
        raw = np.asarray(data[start:stop, :TARGET_CHANNELS], dtype=np.float32)
    elif shape[1] >= stop and shape[0] >= TARGET_CHANNELS:
        # channels x time fallback
        raw = np.asarray(data[:TARGET_CHANNELS, start:stop], dtype=np.float32).T
    else:
        raise ValueError(f"Cannot extract {start}:{stop} first {TARGET_CHANNELS} channels from shape={shape}")

    if raw.shape != (SOURCE_SAMPLES, TARGET_CHANNELS):
        raise ValueError(f"Unexpected raw window shape={raw.shape}")

    x = raw[::DOWNSAMPLE, :]
    if x.shape != (TARGET_SAMPLES, TARGET_CHANNELS):
        raise ValueError(f"Unexpected downsampled shape={x.shape}")

    x = x.T.astype(np.float32, copy=False)
    mean = float(x.mean())
    std = float(x.std())
    if not np.isfinite(mean) or not np.isfinite(std):
        raise ValueError("Non-finite mean/std before normalization")
    x = x - mean
    if std >= 1e-8:
        x = x / std
    return x.astype(np.float32, copy=False)


def render_md(report: dict[str, Any]) -> str:
    lines = [
        "# I-DARE EEG Cache Build Report\n",
        "This report was generated by `scripts/12_build_idare_eeg_cache.py`.\n",
        "No model training was performed.\n",
        "## Status\n",
        f"Status: **{report['status']}**\n",
        "## Configuration\n",
        "```json\n" + json.dumps(safe(report["config"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Outputs\n",
    ]
    for k, v in report["outputs"].items():
        lines.append(f"- {k}: `{v}`")
    lines += ["", "## Counts", "| Item | Value |", "|---|---:|"]
    for k, v in report["counts"].items():
        lines.append(f"| {k} | {v} |")
    lines += [
        "",
        "## Cache\n",
        "```json\n" + json.dumps(safe(report["cache"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Label Counts\n",
        "```json\n" + json.dumps(safe(report["label_counts"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Runtime\n",
        f"- elapsed_sec: `{report['elapsed_sec']:.2f}`\n",
        "## Issues",
    ]
    lines += [f"- {x}" for x in report["issues"]] if report["issues"] else ["- None."]
    lines += ["", "## Warnings"]
    lines += [f"- {x}" for x in report["warnings"]] if report["warnings"] else ["- None."]
    lines += ["", "## Next Step", "Run `scripts/13_validate_idare_eeg_cache.py` before cache-based training.\n"]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--limit", type=int, default=None)
    args = parser.parse_args()

    t0 = time.perf_counter()
    issues: list[str] = []
    warnings: list[str] = []

    if not TRIAL_INDEX.exists():
        raise FileNotFoundError(f"Missing {TRIAL_INDEX}. Run scripts/06_build_idare_trial_index.py first.")
    if OUT_NPY.exists() and not args.force:
        raise FileExistsError(f"Cache exists: {OUT_NPY}. Use --force to rebuild.")

    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(TRIAL_INDEX)
    if args.limit is not None:
        df = df.head(args.limit).copy()
    df = df.reset_index(drop=True)

    required = ["subject_id", "subject_col", "stimulus_id", "raw_event_name", "eeg_file", "eeg_begin_raw", "valence_score", "arousal_score"]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns in trial index: {missing}")

    tmp_npy = OUT_NPY.with_name(OUT_NPY.stem + ".tmp.npy")
    tmp_index = OUT_INDEX.with_name(OUT_INDEX.stem + ".tmp.csv")
    for p in [tmp_npy, tmp_index]:
        if p.exists():
            p.unlink()

    n = int(len(df))
    arr = np.lib.format.open_memmap(tmp_npy, mode="w+", dtype=np.float32, shape=(n, TARGET_CHANNELS, TARGET_SAMPLES))
    rows = []
    extracted = 0
    grouped = list(df.groupby("eeg_file", sort=False))

    print("Building I-DARE EEG cache")
    print(f"rows: {n}")
    print(f"subject files: {len(grouped)}")
    print(f"output: {OUT_NPY}")

    for file_i, (eeg_file, g) in enumerate(grouped, 1):
        eeg_path = Path(str(eeg_file))
        subject = str(g.iloc[0]["subject_col"])
        print(f"[{file_i:03d}/{len(grouped):03d}] {subject}: {len(g)} trials", flush=True)
        try:
            with h5py.File(eeg_path, "r") as h5:
                key = subject_key(h5, subject)
                data = h5[key]["data"]
                for row_i, row in g.iterrows():
                    try:
                        x = extract_window(data, float(row["eeg_begin_raw"]))
                        arr[int(row_i)] = x
                        extracted += 1
                        outrow = {
                            "cache_row": int(row_i),
                            "subject_id": int(row["subject_id"]),
                            "subject_col": str(row["subject_col"]),
                            "stimulus_id": str(row["stimulus_id"]),
                            "raw_event_name": str(row["raw_event_name"]),
                            "eeg_file": str(eeg_path),
                            "eeg_begin_raw": float(row["eeg_begin_raw"]),
                            "valence_score": safe(row["valence_score"]),
                            "arousal_score": safe(row["arousal_score"]),
                        }
                        for task in TASKS:
                            for pol in POLICIES:
                                outrow[f"{task}_{pol}"] = label_from_score(row[f"{task}_score"], pol)
                        rows.append(outrow)
                    except Exception as exc:
                        issues.append(f"row={row_i} subject={subject} stimulus={row.get('stimulus_id')}: {exc!r}")
        except Exception as exc:
            issues.append(f"file={eeg_path}: {exc!r}")

    arr.flush()
    del arr

    index_df = pd.DataFrame(rows).sort_values("cache_row")
    index_df.to_csv(tmp_index, index=False)

    status = "PASSED" if not issues and extracted == n else "FAILED"
    if status == "PASSED":
        if OUT_NPY.exists():
            OUT_NPY.unlink()
        if OUT_INDEX.exists():
            OUT_INDEX.unlink()
        tmp_npy.rename(OUT_NPY)
        tmp_index.rename(OUT_INDEX)
        cache_path = OUT_NPY
        index_path = OUT_INDEX
    else:
        warnings.append("Temporary cache files were kept for debugging.")
        cache_path = tmp_npy
        index_path = tmp_index

    size = cache_path.stat().st_size if cache_path.exists() else 0
    report = {
        "status": status,
        "config": {
            "source_fs": SOURCE_FS,
            "target_fs": TARGET_FS,
            "source_samples": SOURCE_SAMPLES,
            "target_samples": TARGET_SAMPLES,
            "target_channels": TARGET_CHANNELS,
            "downsample": DOWNSAMPLE,
            "normalization": "per-trial global z-score",
        },
        "inputs": {"trial_index": str(TRIAL_INDEX)},
        "outputs": {
            "eeg_cache_npy": str(cache_path),
            "cache_index_csv": str(index_path),
            "build_report_md": str(OUT_MD),
            "build_report_json": str(OUT_JSON),
        },
        "counts": {
            "trial_index_rows": n,
            "extracted_rows": extracted,
            "cache_index_rows": int(len(index_df)),
            "subject_files": len(grouped),
        },
        "cache": {"shape": [n, TARGET_CHANNELS, TARGET_SAMPLES], "dtype": "float32", "file_size": size, "file_size_human": human_size(size)},
        "label_counts": {task: {pol: label_counts(df, task, pol) for pol in POLICIES} for task in TASKS},
        "elapsed_sec": time.perf_counter() - t0,
        "issues": issues,
        "warnings": warnings,
    }

    OUT_JSON.write_text(json.dumps(safe(report), indent=2, ensure_ascii=False), encoding="utf-8")
    OUT_MD.write_text(render_md(report), encoding="utf-8")

    print(f"Wrote: {OUT_MD}")
    print(f"Wrote: {OUT_JSON}")
    print(f"Status: {status}")
    print(f"Rows extracted: {extracted} / {n}")
    print(f"Cache size: {human_size(size)}")
    print(f"Elapsed: {report['elapsed_sec']:.2f}s")
    print(f"Issues: {len(issues)}")
    print(f"Warnings: {len(warnings)}")
    if status != "PASSED":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
