#!/usr/bin/env python3
"""Validate the I-DARE EEG cache. No training is performed."""
from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CACHE_DIR = ROOT / ".cache"
CACHE_NPY = CACHE_DIR / "idare_eeg_windows_32x640_float32.npy"
CACHE_INDEX = CACHE_DIR / "idare_eeg_cache_index.csv"
OUT_JSON = ROOT / "docs" / "idare_eeg_cache_validation.json"
OUT_MD = ROOT / "docs" / "idare_eeg_cache_validation.md"
EXPECTED_ROWS = 2016
EXPECTED_SUFFIX = (32, 640)
LABEL_COLS = [
    "valence_discard_midpoint",
    "valence_midpoint_as_low",
    "valence_midpoint_as_high",
    "arousal_discard_midpoint",
    "arousal_midpoint_as_low",
    "arousal_midpoint_as_high",
]


def safe(v: Any) -> Any:
    if isinstance(v, dict):
        return {str(k): safe(x) for k, x in v.items()}
    if isinstance(v, (list, tuple)):
        return [safe(x) for x in v]
    if isinstance(v, np.ndarray):
        return safe(v.tolist())
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return None if math.isnan(float(v)) else float(v)
    try:
        if pd.isna(v):
            return None
    except Exception:
        pass
    return v


def label_counts(df: pd.DataFrame, col: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for v in df[col].tolist():
        key = "discard" if pd.isna(v) else str(int(float(v)))
        out[key] = out.get(key, 0) + 1
    return dict(sorted(out.items()))


def render_md(report: dict[str, Any]) -> str:
    lines = [
        "# I-DARE EEG Cache Validation\n",
        "This report was generated by `scripts/13_validate_idare_eeg_cache.py`.\n",
        "No model training was performed.\n",
        "## Status\n",
        f"Status: **{report['status']}**\n",
        "## Inputs\n",
    ]
    for k, v in report["inputs"].items():
        lines.append(f"- {k}: `{v}`")
    lines += [
        "",
        "## Cache Summary\n",
        "```json\n" + json.dumps(safe(report["cache"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Label Counts\n",
        "```json\n" + json.dumps(safe(report["label_counts"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Speed Check\n",
        "```json\n" + json.dumps(safe(report["speed_check"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Sample Preview\n",
        "```json\n" + json.dumps(safe(report["sample_preview"]), indent=2, ensure_ascii=False) + "\n```\n",
        "## Issues",
    ]
    lines += [f"- {x}" for x in report["issues"]] if report["issues"] else ["- None."]
    lines += ["", "## Warnings"]
    lines += [f"- {x}" for x in report["warnings"]] if report["warnings"] else ["- None."]
    lines += ["", "## Next Step", "Use this cache for the next EEG-only baseline instead of reading HDF5 files inside each training batch.\n"]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chunk-size", type=int, default=128)
    parser.add_argument("--preview-rows", type=int, default=5)
    parser.add_argument("--speed-rows", type=int, default=256)
    args = parser.parse_args()

    t0 = time.perf_counter()
    issues: list[str] = []
    warnings: list[str] = []

    if not CACHE_NPY.exists():
        raise FileNotFoundError(f"Missing cache: {CACHE_NPY}")
    if not CACHE_INDEX.exists():
        raise FileNotFoundError(f"Missing cache index: {CACHE_INDEX}")

    arr = np.load(CACHE_NPY, mmap_mode="r")
    idx = pd.read_csv(CACHE_INDEX)
    shape = tuple(int(x) for x in arr.shape)

    if len(shape) != 3:
        issues.append(f"Expected 3D array, got shape={shape}")
    if shape[1:] != EXPECTED_SUFFIX:
        issues.append(f"Expected shape suffix {EXPECTED_SUFFIX}, got {shape[1:]}")
    if shape[0] != len(idx):
        issues.append(f"Cache rows {shape[0]} != index rows {len(idx)}")
    if shape[0] != EXPECTED_ROWS:
        warnings.append(f"Expected full-cache rows {EXPECTED_ROWS}, got {shape[0]}")

    finite_ok = True
    global_min = float("inf")
    global_max = float("-inf")
    means: list[float] = []
    stds: list[float] = []

    for start in range(0, shape[0], args.chunk_size):
        stop = min(start + args.chunk_size, shape[0])
        chunk = np.asarray(arr[start:stop], dtype=np.float32)
        if not np.isfinite(chunk).all():
            finite_ok = False
            issues.append(f"Non-finite values in chunk {start}:{stop}")
            break
        global_min = min(global_min, float(chunk.min()))
        global_max = max(global_max, float(chunk.max()))
        flat = chunk.reshape(chunk.shape[0], -1)
        means.extend([float(x) for x in flat.mean(axis=1)])
        stds.extend([float(x) for x in flat.std(axis=1)])

    means_arr = np.asarray(means, dtype=np.float64)
    stds_arr = np.asarray(stds, dtype=np.float64)

    sample_preview = []
    for row_i in range(min(args.preview_rows, shape[0])):
        row = idx.iloc[row_i].to_dict()
        x = np.asarray(arr[row_i], dtype=np.float32)
        sample_preview.append({
            "cache_row": row_i,
            "subject_id": safe(row.get("subject_id")),
            "stimulus_id": safe(row.get("stimulus_id")),
            "shape": list(x.shape),
            "mean": float(x.mean()),
            "std": float(x.std()),
            "min": float(x.min()),
            "max": float(x.max()),
        })

    speed_n = min(args.speed_rows, shape[0])
    s0 = time.perf_counter()
    batch = np.asarray(arr[:speed_n], dtype=np.float32)
    _ = float(batch.mean())
    speed_elapsed = time.perf_counter() - s0

    counts = {}
    for col in LABEL_COLS:
        if col in idx.columns:
            counts[col] = label_counts(idx, col)
        else:
            issues.append(f"Missing label column: {col}")

    report = {
        "status": "PASSED" if not issues else "FAILED",
        "inputs": {"cache_npy": str(CACHE_NPY), "cache_index": str(CACHE_INDEX)},
        "outputs": {"validation_md": str(OUT_MD), "validation_json": str(OUT_JSON)},
        "cache": {
            "shape": list(shape),
            "dtype": str(arr.dtype),
            "finite_ok": finite_ok,
            "global_min": global_min,
            "global_max": global_max,
            "per_trial_mean_abs_max": float(np.max(np.abs(means_arr))) if len(means_arr) else None,
            "per_trial_std_min": float(stds_arr.min()) if len(stds_arr) else None,
            "per_trial_std_max": float(stds_arr.max()) if len(stds_arr) else None,
        },
        "label_counts": counts,
        "speed_check": {
            "rows_read": speed_n,
            "elapsed_sec": speed_elapsed,
            "rows_per_sec": float(speed_n / speed_elapsed) if speed_elapsed > 0 else None,
        },
        "sample_preview": sample_preview,
        "elapsed_sec": time.perf_counter() - t0,
        "issues": issues,
        "warnings": warnings,
    }

    OUT_JSON.write_text(json.dumps(safe(report), indent=2, ensure_ascii=False), encoding="utf-8")
    OUT_MD.write_text(render_md(report), encoding="utf-8")

    print(f"Wrote: {OUT_MD}")
    print(f"Wrote: {OUT_JSON}")
    print(f"Status: {report['status']}")
    print(f"Shape: {report['cache']['shape']}")
    print(f"Finite OK: {report['cache']['finite_ok']}")
    print(f"Rows/sec: {report['speed_check']['rows_per_sec']:.2f}")
    print(f"Issues: {len(issues)}")
    print(f"Warnings: {len(warnings)}")
    if report["status"] != "PASSED":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
