#!/usr/bin/env python3
"""Build a NumPy EEG-window cache from DEAP preprocessed Python .dat files.

This script is smoke-first. It does not train a model.

DEAP preprocessed Python expected shape per subject:
- data:   [40, 40, 8064]
- labels: [40, 4]

Signal convention:
- first 32 channels are EEG
- first 384 samples are 3s baseline at 128Hz
- remaining 7680 samples are 60s stimulus at 128Hz
- stimulus is split into 12 non-overlapping 5s windows: 12 x 640

Preprocessing:
- subtract per-channel baseline mean from each 60s stimulus trial
- split into windows
- apply per-window global z-score
"""

from __future__ import annotations

import argparse
import json
import pickle
import time
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from numpy.lib.format import open_memmap


ROOT = Path(__file__).resolve().parents[1]

DEFAULT_DEAP_DIR = Path("/mnt/HDD/AliWorks/DEAP/data_preprocessed_python")
DEFAULT_OUT_NPY = ROOT / ".cache" / "deap_eeg_windows_32x640_float32_smoke.npy"
DEFAULT_OUT_INDEX = ROOT / ".cache" / "deap_eeg_cache_index_smoke.csv"
DEFAULT_OUT_MD = ROOT / "docs" / "deap_eeg_cache_build_smoke.md"
DEFAULT_OUT_JSON = ROOT / "docs" / "deap_eeg_cache_build_smoke.json"

SOURCE_FS = 128.0
TARGET_FS = 128.0
EEG_CHANNELS = 32
ALL_CHANNELS = 40
TRIALS_PER_SUBJECT = 40
SAMPLES_TOTAL = 8064
BASELINE_SAMPLES = 384
STIMULUS_SAMPLES = 7680
WINDOW_SAMPLES = 640
WINDOWS_PER_TRIAL = 12
LABEL_COLUMNS = ["valence", "arousal", "dominance", "liking"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--deap-dir", type=Path, default=DEFAULT_DEAP_DIR)
    parser.add_argument("--out-npy", type=Path, default=DEFAULT_OUT_NPY)
    parser.add_argument("--out-index", type=Path, default=DEFAULT_OUT_INDEX)
    parser.add_argument("--out-md", type=Path, default=DEFAULT_OUT_MD)
    parser.add_argument("--out-json", type=Path, default=DEFAULT_OUT_JSON)
    parser.add_argument(
        "--limit-subjects",
        type=int,
        default=None,
        help="Optional smoke limit on number of subject files.",
    )
    parser.add_argument(
        "--no-baseline-correction",
        action="store_true",
        help="Do not subtract the 3s baseline mean. Not recommended for main DEAP cache.",
    )
    return parser.parse_args()


def load_deap_dat(path: Path) -> dict[str, Any]:
    with path.open("rb") as f:
        return pickle.load(f, encoding="latin1")


def subject_id_from_file(path: Path) -> int:
    stem = path.stem
    if not (len(stem) == 3 and stem.startswith("s") and stem[1:].isdigit()):
        raise ValueError(f"Unexpected DEAP subject filename: {path.name}")
    return int(stem[1:])


def bin_label(score: float, policy: str) -> float:
    if policy == "discard_midpoint":
        if np.isclose(score, 5.0):
            return float("nan")
        return float(score > 5.0)
    if policy == "midpoint_as_low":
        return float(score > 5.0)
    if policy == "midpoint_as_high":
        return float(score >= 5.0)
    raise ValueError(f"Unknown label policy: {policy}")


def finite_summary(values: list[float]) -> dict[str, float | None]:
    arr = np.asarray(values, dtype=np.float64)
    arr = arr[np.isfinite(arr)]
    if arr.size == 0:
        return {"mean": None, "median": None, "min": None, "max": None}
    return {
        "mean": float(arr.mean()),
        "median": float(np.median(arr)),
        "min": float(arr.min()),
        "max": float(arr.max()),
    }


def label_counts(index_df: pd.DataFrame) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for task in ["valence", "arousal", "dominance", "liking"]:
        out[task] = {}
        for policy in ["discard_midpoint", "midpoint_as_low", "midpoint_as_high"]:
            col = f"{task}_{policy}"
            s = index_df[col]
            counts = {
                "0": int((s == 0).sum()),
                "1": int((s == 1).sum()),
            }
            if policy == "discard_midpoint":
                counts["discard"] = int(s.isna().sum())
            out[task][policy] = counts
    return out


def write_report_md(report: dict[str, Any], path: Path) -> None:
    lines: list[str] = []
    lines.append("# DEAP EEG Cache Build Smoke Report")
    lines.append("")
    lines.append("This report was generated by `scripts/25_build_deap_eeg_cache.py`.")
    lines.append("")
    lines.append("No model training was performed.")
    lines.append("")
    lines.append("## Status")
    lines.append("")
    lines.append(f"Status: **{report['status']}**")
    lines.append("")
    lines.append("## Configuration")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(report["config"], indent=2))
    lines.append("```")
    lines.append("")
    lines.append("## Inputs")
    lines.append("")
    lines.append(f"- deap_dir: `{report['inputs']['deap_dir']}`")
    lines.append("")
    lines.append("## Outputs")
    lines.append("")
    for k, v in report["outputs"].items():
        lines.append(f"- {k}: `{v}`")
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append("| Item | Value |")
    lines.append("|---|---:|")
    for k, v in report["counts"].items():
        lines.append(f"| {k} | {v} |")
    lines.append("")
    lines.append("## Cache")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(report["cache"], indent=2))
    lines.append("```")
    lines.append("")
    lines.append("## Baseline / Window Diagnostics")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(report["diagnostics"], indent=2))
    lines.append("```")
    lines.append("")
    lines.append("## Label Counts")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(report["label_counts"], indent=2))
    lines.append("```")
    lines.append("")
    lines.append("## Runtime")
    lines.append("")
    lines.append(f"- elapsed_sec: `{report['runtime']['elapsed_sec']:.2f}`")
    lines.append("")
    lines.append("## Issues")
    if report["issues"]:
        for issue in report["issues"]:
            lines.append(f"- {issue}")
    else:
        lines.append("- None.")
    lines.append("")
    lines.append("## Warnings")
    if report["warnings"]:
        for warning in report["warnings"]:
            lines.append(f"- {warning}")
    else:
        lines.append("- None.")
    lines.append("")
    lines.append("## Next Step")
    lines.append("")
    lines.append("Validate this smoke output before building a full DEAP cache or running training.")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    t0 = time.perf_counter()

    args.out_npy.parent.mkdir(parents=True, exist_ok=True)
    args.out_index.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.parent.mkdir(parents=True, exist_ok=True)

    subject_files = sorted(args.deap_dir.glob("s*.dat"))
    if args.limit_subjects is not None:
        subject_files = subject_files[: args.limit_subjects]

    issues: list[str] = []
    warnings: list[str] = []

    if not subject_files:
        issues.append(f"No DEAP .dat files found in {args.deap_dir}")

    total_rows = len(subject_files) * TRIALS_PER_SUBJECT * WINDOWS_PER_TRIAL
    cache = open_memmap(
        args.out_npy,
        mode="w+",
        dtype="float32",
        shape=(total_rows, EEG_CHANNELS, WINDOW_SAMPLES),
    )

    rows: list[dict[str, Any]] = []
    baseline_mean_global_values: list[float] = []
    baseline_mean_abs_values: list[float] = []
    corrected_mean_before_zscore_values: list[float] = []
    corrected_std_before_zscore_values: list[float] = []
    window_mean_after_zscore_values: list[float] = []
    window_std_after_zscore_values: list[float] = []

    cache_row = 0

    print("Building DEAP EEG cache")
    print(f"DEAP dir: {args.deap_dir}")
    print(f"subject files: {len(subject_files)}")
    print(f"output: {args.out_npy}")

    for file_i, path in enumerate(subject_files, start=1):
        sid = subject_id_from_file(path)
        print(f"[{file_i:03d}/{len(subject_files):03d}] {path.name}")

        try:
            obj = load_deap_dat(path)
        except Exception as exc:
            issues.append(f"{path.name}: failed to load: {exc!r}")
            continue

        data = obj.get("data")
        labels = obj.get("labels")

        if not isinstance(data, np.ndarray):
            issues.append(f"{path.name}: data is not ndarray")
            continue
        if not isinstance(labels, np.ndarray):
            issues.append(f"{path.name}: labels is not ndarray")
            continue

        if tuple(data.shape) != (TRIALS_PER_SUBJECT, ALL_CHANNELS, SAMPLES_TOTAL):
            issues.append(f"{path.name}: unexpected data shape {list(data.shape)}")
            continue
        if tuple(labels.shape) != (TRIALS_PER_SUBJECT, len(LABEL_COLUMNS)):
            issues.append(f"{path.name}: unexpected labels shape {list(labels.shape)}")
            continue

        if not np.isfinite(data).all():
            issues.append(f"{path.name}: data contains NaN/Inf")
            continue
        if not np.isfinite(labels).all():
            issues.append(f"{path.name}: labels contains NaN/Inf")
            continue

        for trial_i in range(TRIALS_PER_SUBJECT):
            eeg = data[trial_i, :EEG_CHANNELS, :].astype(np.float32, copy=False)
            baseline = eeg[:, :BASELINE_SAMPLES]
            stimulus = eeg[:, BASELINE_SAMPLES:]

            if stimulus.shape != (EEG_CHANNELS, STIMULUS_SAMPLES):
                issues.append(f"{path.name} trial {trial_i}: bad stimulus shape {list(stimulus.shape)}")
                continue

            baseline_mean = baseline.mean(axis=1, keepdims=True)
            baseline_mean_global = float(baseline_mean.mean())
            baseline_mean_abs = float(np.abs(baseline_mean).mean())

            if args.no_baseline_correction:
                corrected = stimulus.copy()
                baseline_correction = "none"
            else:
                corrected = stimulus - baseline_mean
                baseline_correction = "subtract_deap_3s_baseline_per_channel_mean_then_window_global_zscore"

            corrected_mean = float(corrected.mean())
            corrected_std = float(corrected.std())

            baseline_mean_global_values.append(baseline_mean_global)
            baseline_mean_abs_values.append(baseline_mean_abs)
            corrected_mean_before_zscore_values.append(corrected_mean)
            corrected_std_before_zscore_values.append(corrected_std)

            scores = {
                "valence_score": float(labels[trial_i, 0]),
                "arousal_score": float(labels[trial_i, 1]),
                "dominance_score": float(labels[trial_i, 2]),
                "liking_score": float(labels[trial_i, 3]),
            }

            for window_i in range(WINDOWS_PER_TRIAL):
                start = window_i * WINDOW_SAMPLES
                end = start + WINDOW_SAMPLES
                window = corrected[:, start:end].astype(np.float32, copy=False)

                mean = float(window.mean())
                std = float(window.std())
                if std < 1e-8:
                    issues.append(f"{path.name} trial {trial_i} window {window_i}: near-zero std")
                    z = window - mean
                else:
                    z = (window - mean) / std

                cache[cache_row] = z.astype(np.float32, copy=False)

                window_mean_after_zscore_values.append(float(cache[cache_row].mean()))
                window_std_after_zscore_values.append(float(cache[cache_row].std()))

                row: dict[str, Any] = {
                    "cache_row": cache_row,
                    "subject_id": sid,
                    "subject_file": path.name,
                    "trial_id": trial_i + 1,
                    "trial_index_0based": trial_i,
                    "window_id": window_i + 1,
                    "window_index_0based": window_i,
                    "window_start_sample_128hz": int(BASELINE_SAMPLES + start),
                    "window_end_sample_128hz_exclusive": int(BASELINE_SAMPLES + end),
                    "baseline_correction": baseline_correction,
                    **scores,
                    "diag_baseline_mean_global": baseline_mean_global,
                    "diag_baseline_mean_abs_mean": baseline_mean_abs,
                    "diag_corrected_mean_before_zscore": corrected_mean,
                    "diag_corrected_std_before_zscore": corrected_std,
                }

                for task in ["valence", "arousal", "dominance", "liking"]:
                    score = row[f"{task}_score"]
                    for policy in ["discard_midpoint", "midpoint_as_low", "midpoint_as_high"]:
                        row[f"{task}_{policy}"] = bin_label(score, policy)

                rows.append(row)
                cache_row += 1

    cache.flush()

    index_df = pd.DataFrame(rows)
    index_df.to_csv(args.out_index, index=False)

    actual_shape = list(np.load(args.out_npy, mmap_mode="r").shape)
    status = "PASSED" if not issues and cache_row == total_rows else "CHECK_NEEDED"

    report = {
        "status": status,
        "config": {
            "source_fs": SOURCE_FS,
            "target_fs": TARGET_FS,
            "input": "DEAP data_preprocessed_python",
            "source_data_shape_per_subject": [TRIALS_PER_SUBJECT, ALL_CHANNELS, SAMPLES_TOTAL],
            "eeg_channels": EEG_CHANNELS,
            "baseline_samples": BASELINE_SAMPLES,
            "stimulus_samples": STIMULUS_SAMPLES,
            "window_samples": WINDOW_SAMPLES,
            "windows_per_trial": WINDOWS_PER_TRIAL,
            "baseline_correction": "none" if args.no_baseline_correction else "subtract 3s baseline per-channel mean",
            "normalization": "per-window global z-score",
            "limit_subjects": args.limit_subjects,
        },
        "inputs": {
            "deap_dir": str(args.deap_dir),
        },
        "outputs": {
            "eeg_cache_npy": str(args.out_npy),
            "cache_index_csv": str(args.out_index),
            "build_report_md": str(args.out_md),
            "build_report_json": str(args.out_json),
        },
        "counts": {
            "subject_files": len(subject_files),
            "expected_rows": total_rows,
            "extracted_rows": cache_row,
            "cache_index_rows": len(index_df),
        },
        "cache": {
            "shape": actual_shape,
            "dtype": "float32",
            "file_size": args.out_npy.stat().st_size if args.out_npy.exists() else None,
            "file_size_human": f"{args.out_npy.stat().st_size / (1024 * 1024):.2f} MB" if args.out_npy.exists() else None,
        },
        "diagnostics": {
            "baseline_mean_global": finite_summary(baseline_mean_global_values),
            "baseline_mean_abs_mean": finite_summary(baseline_mean_abs_values),
            "corrected_mean_before_zscore": finite_summary(corrected_mean_before_zscore_values),
            "corrected_std_before_zscore": finite_summary(corrected_std_before_zscore_values),
            "window_mean_after_zscore": finite_summary(window_mean_after_zscore_values),
            "window_std_after_zscore": finite_summary(window_std_after_zscore_values),
        },
        "label_counts": label_counts(index_df) if len(index_df) else {},
        "runtime": {
            "elapsed_sec": time.perf_counter() - t0,
        },
        "issues": issues,
        "warnings": warnings,
    }

    args.out_json.write_text(json.dumps(report, indent=2), encoding="utf-8")
    write_report_md(report, args.out_md)

    print(f"Wrote: {args.out_md}")
    print(f"Wrote: {args.out_json}")
    print(f"Status: {status}")
    print(f"Rows extracted: {cache_row} / {total_rows}")
    print(f"Cache size: {report['cache']['file_size_human']}")
    print(f"Elapsed: {report['runtime']['elapsed_sec']:.2f}s")
    print(f"Issues: {len(issues)}")
    print(f"Warnings: {len(warnings)}")

    return 0 if status == "PASSED" else 1


if __name__ == "__main__":
    raise SystemExit(main())
